version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=ws://localhost:5089 # Modifier le port ici

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5089:5000" # Exposer le port 5000 du conteneur sur le port 5089 de l'hôte
    environment:
      - PASSWORD=HXM